firstName = input("Enter first name: ")
lastName = input("Enter last name: ")
birthYear = input("Enter birth year: ")
City = input("Enter city: ")
age = 2026 - int(birthYear)
print(f"Your name is {firstName} {lastName}, you were born in {birthYear}, and you are {age} years old. from {City}.")